# Generated by Django 5.2.3 on 2025-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactFormTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('email_field_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_field_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_field_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('message_field_placeholder', models.CharField(blank=True, max_length=100, null=True)),
                ('submit_button_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
