# Generated by Django 5.2.3 on 2025-06-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactformtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformtitle',
            name='contact_form_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
