# Generated by Django 5.2.3 on 2025-06-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contactformtitle_contact_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformtitle',
            name='email_title',
            field=models.CharField(blank=True, default='Email', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactformtitle',
            name='location_title',
            field=models.CharField(blank=True, default='Location', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactformtitle',
            name='phone_title',
            field=models.CharField(blank=True, default='Phone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='contact_form_title',
            field=models.CharField(blank=True, default='Have Any Questions', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='email_field_placeholder',
            field=models.CharField(blank=True, default='Enter your email', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='message_field_placeholder',
            field=models.CharField(blank=True, default='Enter your message', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='name_field_placeholder',
            field=models.CharField(blank=True, default='Enter your name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='phone_field_placeholder',
            field=models.CharField(blank=True, default='Enter your phone', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='subject_field_placeholder',
            field=models.CharField(blank=True, default='Enter your subject', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactformtitle',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Send Message', max_length=100, null=True),
        ),
    ]
