# Generated by Django 5.2.3 on 2025-06-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contactformtitle_email_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberFormTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_title', models.CharField(blank=True, default='Get In Touch', max_length=100, null=True)),
                ('middle_title', models.CharField(blank=True, default='Subscribe Our', max_length=100, null=True)),
                ('bottom_title', models.CharField(blank=True, default='Newsletter', max_length=100, null=True)),
                ('email_field_placeholder', models.CharField(blank=True, default='Enter your email', max_length=100, null=True)),
                ('submit_button_text', models.CharField(blank=True, default='Subscribe', max_length=100, null=True)),
            ],
        ),
    ]
