# Generated by Django 5.2.3 on 2025-06-17 14:43

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.CharField(blank=True, max_length=200, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('ranking_number', models.IntegerField(blank=True, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=200, null=True)),
                ('experience', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='AboutSection/')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to='AboutSection/')),
                ('video_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '3. About Section',
            },
        ),
        migrations.CreateModel(
            name='clientSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Clients/')),
            ],
            options={
                'verbose_name_plural': '6.Client Section',
            },
        ),
        migrations.CreateModel(
            name='funFactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontawesome_icon_class', models.CharField(blank=True, max_length=200, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('count_after', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': '4. Fun Fact Section',
            },
        ),
        migrations.CreateModel(
            name='homePageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='projectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='serviceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500, null=True)),
                ('fontawesome_icon_class', models.CharField(blank=True, max_length=100, null=True)),
                ('detail_page_image', models.ImageField(blank=True, null=True, upload_to='Services/')),
                ('detail_page_description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('show_call_now_widget', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '2. Service Section',
            },
        ),
        migrations.CreateModel(
            name='sliderSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Home/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('button1_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button1_url', models.CharField(blank=True, max_length=500, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_url', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '1. Slider Section',
            },
        ),
        migrations.CreateModel(
            name='testimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Testimonials/')),
                ('star', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '7.Testimonial Section',
            },
        ),
        migrations.CreateModel(
            name='projectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Projects/')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('client', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.projectcategory')),
            ],
            options={
                'verbose_name_plural': '5.Project Section',
            },
        ),
    ]
