# Generated by Django 5.2.3 on 2025-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogsectiontitle_clientsectiontitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceSectionTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_small', models.CharField(blank=True, max_length=100, null=True)),
                ('title_big', models.CharField(blank=True, max_length=100, null=True)),
                ('service_card_more_text', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
