# Generated by Django 5.2.3 on 2025-06-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='headerFooterSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_button_text', models.CharField(blank=True, max_length=200, null=True)),
                ('header_button_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('footer_col1_description', models.TextField(blank=True, null=True)),
                ('social1_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('social1_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('social2_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('social2_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('social3_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('social3_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('social4_icon', models.CharField(blank=True, max_length=200, null=True)),
                ('social4_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('footer_copyright', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeoSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=500, null=True)),
                ('tag_line', models.CharField(blank=True, max_length=600, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('seo_keywords', models.TextField(blank=True, default='software,application,marketer,developer', null=True)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='app_config/')),
            ],
        ),
        migrations.CreateModel(
            name='templateSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template1', models.BooleanField(default=True)),
                ('template2', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='websiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Application Name', max_length=500, null=True)),
                ('author', models.CharField(blank=True, default='Author Name', max_length=200, null=True)),
                ('currency_name', models.CharField(blank=True, default='Currency Name', max_length=100, null=True)),
                ('currency_symbol', models.CharField(blank=True, default='Currency Symbol', max_length=150, null=True)),
                ('show_call_now_widget', models.BooleanField(default=True)),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='app_config/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='app_config/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='app_config/')),
                ('email_address', models.EmailField(blank=True, default='test@gmail.com', max_length=500, null=True)),
                ('phone', models.CharField(blank=True, default='88012454784', max_length=20, null=True)),
                ('price_ragne', models.CharField(blank=True, default='60$ to 7000$', max_length=50, null=True)),
                ('address', models.CharField(blank=True, default='Your Address', max_length=700, null=True)),
                ('city', models.CharField(blank=True, default='Your City', max_length=200, null=True)),
                ('country', models.CharField(blank=True, default='Your Country', max_length=300, null=True)),
                ('state', models.CharField(blank=True, default='Your State', max_length=200, null=True)),
                ('postal', models.IntegerField(blank=True, default=12345, null=True)),
                ('map_iframe', models.TextField(blank=True, null=True)),
                ('contact_form_image', models.ImageField(blank=True, null=True, upload_to='app_config/')),
                ('analytics_code', models.CharField(blank=True, default='GA_MEASUREMENT_ID', max_length=300, null=True)),
                ('facebook_pixel_code', models.TextField(blank=True, null=True)),
                ('facebook_chat_code', models.TextField(blank=True, null=True)),
                ('whatsapp_is_active', models.BooleanField(default=True)),
                ('facebook_chat_is_active', models.BooleanField(default=True)),
                ('slider_particle_is_active', models.BooleanField(default=True)),
                ('default_menu_is_active', models.BooleanField(default=True)),
                ('magic_cursor_is_active', models.BooleanField(default=True)),
                ('custom_css', models.TextField(blank=True, null=True)),
                ('custom_js', models.TextField(blank=True, null=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=500, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=500, null=True)),
                ('twilio_from_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
