# Generated by Django 5.2.3 on 2025-06-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_websitesetting_address_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websitesetting',
            name='address_title',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='email_title',
        ),
        migrations.RemoveField(
            model_name='websitesetting',
            name='phone_title',
        ),
    ]
