# Generated by Django 5.2.3 on 2025-06-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_websitesetting_address_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitesetting',
            name='primary_color',
            field=models.CharField(blank=True, default='75dab4', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websitesetting',
            name='secondary_color',
            field=models.CharField(blank=True, default='75dab4', max_length=100, null=True),
        ),
    ]
