# Generated by Django 5.2.3 on 2025-06-23 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_websitesetting_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='custom_css',
            field=models.TextField(blank=True, default='Custom CSS', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='custom_js',
            field=models.TextField(blank=True, default='Custom JS', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='facebook_chat_code',
            field=models.TextField(blank=True, default='Facebook Chat Code', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='facebook_pixel_code',
            field=models.TextField(blank=True, default='Facebook Pixel Code', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='map_iframe',
            field=models.TextField(blank=True, default='Map Iframe', null=True),
        ),
    ]
