# Generated by Django 5.2.3 on 2025-06-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_websitesetting_custom_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='custom_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='custom_js',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='facebook_chat_code',
            field=models.TextField(blank=True, default='<script></script>', null=True),
        ),
        migrations.AlterField(
            model_name='websitesetting',
            name='facebook_pixel_code',
            field=models.TextField(blank=True, default='<script></script>', null=True),
        ),
    ]
