# Generated by Django 5.2.3 on 2025-06-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_alter_websitesetting_custom_css_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contacts', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_project_title',
            field=models.CharField(blank=True, default='Recent Projects', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='footer_service_title',
            field=models.CharField(blank=True, default='Our Services', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='privacy_policy_title',
            field=models.CharField(blank=True, default='Privacy Policy', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='headerfootersetting',
            name='terms_and_conditions_title',
            field=models.CharField(blank=True, default='Terms & Conditions', max_length=200, null=True),
        ),
    ]
