# Generated by Django 5.2.3 on 2025-06-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_headerfootersetting_footer_contact_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetting',
            name='secondary_color',
            field=models.CharField(blank=True, default='#1a1a1a', max_length=100, null=True),
        ),
    ]
